import { createAgentLogger } from '../logger/logger';
import { githubService } from '../services/github.service';
import { Task, TestResults } from '../types';

const logger = createAgentLogger('alexa-pr');

export class PullRequestAgent {
  async create(task: Task): Promise<string> {
    const testResults = task.payload.testResults;
    if (!testResults?.passed) {
      throw new Error('Alexa safeguard: refusing to open a PR because tests did not pass.');
    }

    const head = task.payload.fixBranch;
    if (!head) {
      throw new Error('No fix branch was supplied for PR creation.');
    }

    const base = task.payload.baseBranch || task.payload.branch || (await githubService.getDefaultBranch(task.payload.repository));
    const confidence = task.payload.confidence ?? 50;
    const draft = confidence < 70;

    await githubService.pushBranch(task.payload.repository, head);
    const prUrl = await githubService.createPullRequest(task.payload.repository, {
      title: `Automated fix: ${task.payload.title || task.payload.eventType}`,
      body: this.createBody(task, testResults, confidence),
      head,
      base,
      draft
    });

    logger.info('Pull request created', { prUrl, draft, confidence }, task.id);
    return prUrl;
  }

  private createBody(task: Task, testResults: TestResults, confidence: number): string {
    const files = (task.payload.files ?? []).map(file => `- ${file}`).join('\n') || '- No files listed';
    const findings = (task.payload.reviewResults ?? [])
      .map(result => `- ${result.severity.toUpperCase()} ${result.file}:${result.line} ${result.message}`)
      .join('\n') || '- No review findings supplied';

    return [
      '## Summary',
      task.payload.summary || 'Automated fix generated by the Multi-AI-Agent pipeline.',
      '',
      '## Changes',
      files,
      '',
      '## Review Context',
      findings,
      '',
      '## Test Results',
      `- ${testResults.install.command}: ${this.status(testResults.install.exitCode)}`,
      `- ${testResults.build.command}: ${this.status(testResults.build.exitCode)}`,
      `- ${testResults.lint.command}: ${this.status(testResults.lint.exitCode)}`,
      `- ${testResults.test.command}: ${this.status(testResults.test.exitCode)}`,
      '',
      `Confidence: ${confidence}%`,
      confidence < 70 ? 'This PR is a draft because confidence is below 70%.' : 'This PR is ready for review.'
    ].join('\n');
  }

  private status(exitCode: number): string {
    return exitCode === 0 ? 'passed' : `failed (${exitCode})`;
  }
}

export const pullRequestAgent = new PullRequestAgent();
